// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuCE6PkFCUz36iJVsTI6PRGMFKECAgcwU',
    appId: '1:5423202721:web:9b24cfd64e994043c20be0',
    messagingSenderId: '5423202721',
    projectId: 'test-app1-73c0d',
    authDomain: 'test-app1-73c0d.firebaseapp.com',
    storageBucket: 'test-app1-73c0d.firebasestorage.app',
    measurementId: 'G-JZRRBB2RQQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnQburCVKSQhOh32cdvnIErsKO8FscXHo',
    appId: '1:5423202721:android:bdbfa6b5cae0165dc20be0',
    messagingSenderId: '5423202721',
    projectId: 'test-app1-73c0d',
    storageBucket: 'test-app1-73c0d.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuCE6PkFCUz36iJVsTI6PRGMFKECAgcwU',
    appId: '1:5423202721:web:f225c01dc487a75cc20be0',
    messagingSenderId: '5423202721',
    projectId: 'test-app1-73c0d',
    authDomain: 'test-app1-73c0d.firebaseapp.com',
    storageBucket: 'test-app1-73c0d.firebasestorage.app',
    measurementId: 'G-ZEWX4YMJCW',
  );
}
